---
- hosts: all
  gather_facts: no
  connection: local

  tasks:

  - name: execute cli command
    ios_command:
      commands:
        - command: "{{ cmd }}"
      provider: "{{ cli }}"
    register: cmd_output

  - name: save output to file
    copy:
      content: "{{ cmd_output.stdout[0] }}"
      dest: "output/{{ inventory_hostname }}.txt"

