---
- hosts: access-nu
  gather_facts: no
  connection: local

  tasks:

  #- name: check for vlan "{{ vlan_id }}"
  - name: check for vlan 3300
    ios_command:
      commands: "show vlan id 3300"
      provider: "{{ provider }}"
    ignore_errors: yes
    register: sh_vlan_output

  - set_fact:
      vlan_exists: false
    when: sh_vlan_output.failed is defined

  - set_fact:
      vlan_exists: true
    when: sh_vlan_output.failed isundefined

  - name: Debug registered variables
    debug: var=vlan_exists

